/** Electrobun configuration is kept in the repository even while the pinned
 * SDK is selected. The package-local Electrobun CLI consumes this file. */
import { readFileSync } from 'node:fs';
import type { ElectrobunConfig } from 'electrobun';

const packageJson = JSON.parse(
  readFileSync(new URL('./package.json', import.meta.url), 'utf8'),
) as { version: string };
export default {
  app: {
    name: 'Pixel Agents',
    identifier: 'com.pixelagents.desktop',
    version: packageJson.version,
  },
  build: {
    mainProcess: 'cottontail',
    cottontail: { entrypoint: 'desktop/src/main.ts' },
    copy: {
      'dist/desktop-view': 'views/mainview',
      'dist/desktop-assets': 'assets',
      'dist/desktop-hooks': 'hooks',
    },
    // Generated by `npm run icon` from assets/pixel-agent-logo.png and committed.
    // macOS reads the .iconset folder (converted with iconutil on a macOS host); Windows converts
    // the PNG to .ico; Linux uses the PNG for the desktop entry, window and taskbar icons.
    mac: { bundleCEF: true, defaultRenderer: 'cef', icons: 'assets/desktop-icons/icon.iconset' },
    win: { bundleCEF: true, defaultRenderer: 'cef', icon: 'assets/desktop-icons/icon.png' },
    linux: { bundleCEF: true, defaultRenderer: 'cef', icon: 'assets/desktop-icons/icon.png' },
  },
  runtime: { exitOnLastWindowClosed: false },
} satisfies ElectrobunConfig;
